image: python:3.9-slim

stages:
  - test
  - build

run_unit_tests:
  stage: test
  variables:
    SECRET_KEY: t3st1ng-SEcr3+-k3y
  before_script:
    - pip install -r requirements.txt
  script:
    - python manage.py test
  only:
    refs:
      - main
      - merge_requests

check_code_styling:
  stage: test
  before_script:
    - pip install flake8 isort
  script:
    - flake8 --exit-zero --max-line-length 120 --exclude *migrations*
    - python -m isort . --line-length 120 --check-only --skip-glob '*migrations*'
  only:
    refs:
      - merge_requests

check_requirements:
  stage: test
  before_script:
    - pip install safety
  script:
    - safety check -r requirements.txt
  only:
    refs:
      - merge_requests

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile.prod -t $CI_REGISTRY_IMAGE/subredditlog:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE/subredditlog:latest .
    - docker push --all-tags $CI_REGISTRY_IMAGE/subredditlog
    - docker build -t $CI_REGISTRY_IMAGE/subredditlog-nginx:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE/subredditlog-nginx:latest nginx/
    - docker push --all-tags $CI_REGISTRY_IMAGE/subredditlog-nginx
  only:
    refs:
      - tags
