version: '3.7'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - psql_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  psql_data:
