# Generated by Django 3.1.6 on 2021-02-08 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(help_text='The name of the rule', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Text to further explain or define the rule')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(db_index=True, max_length=20)),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Warn'), (2, 'Temporary Ban'), (3, 'Permanent Ban')], default=1)),
                ('ban_length', models.PositiveSmallIntegerField(default=None, help_text='The length of a temporary ban', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='A private note to attach to this entry.')),
                ('moderator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='entries.rule')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
