name: Build and Push Docker Images
on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: seancallaway
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Sanitize Repo Slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ env.REGISTRY }}/${{ github.repository }}'.toLowerCase()

      - name: Build and Push Main Image
        id: main_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          tags: ${{ steps.repo_slug.outputs.result }}:${{ github.event.release.tag_name }}
          push: true

      - name: Build and Push Nginx Image
        id: nginx_build
        uses: docker/build-push-action@v2
        with:
          context: nginx/
          tags: ${{ steps.repo_slug.outputs.result }}-nginx:${{ github.event.release.tag_name }}
          push: true
