name: Build and Push Docker Images
on:
  push:
    tags:
      - v*
    branches:
      - 35/docker_build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: seancallaway/subredditlog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Build and Push Main Image
        id: main_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          #tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true

      - name: Build and Push Nginx Image
        id: nginx_build
        uses: docker/build-push-action@v2
        with:
          context: nginx/
          #tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx:${{ github.event.release.tag_name }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx:latest
          push: true
