name: Django Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9-slim-bullseye
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        env:
          SECRET_KEY: t3st1ng-SEcr3+-k3y
        run: python manage.py test
